export const ROLES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Java Developer",
  "Python Developer",
  "React Developer",
  "Node.js Developer",
  "AI Engineer",
  "Machine Learning Engineer",
  "Data Analyst",
  "Data Scientist",
  "Cyber Security Engineer",
  "QA Engineer",
  "Automation Tester",
];